title: My Blag
author: feature-creature
email: jdema003@gold.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  my blag about everything

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
